The PYFILE variable hasnt't been assigned. should I assign it?

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,8 @@
-#!/usr/bin/python3
-print("Best School")
+#!/bin/bash
+
+if [ -z "$PYFILE" ]; then
+    echo "error"
+    exit 1
+else
+    python3 "$PYFILE"
+fi
